modified network

diff --git a/roles/kubernetes/tasks/tools.yaml b/roles/kubernetes/tasks/tools.yaml
--- a/roles/kubernetes/tasks/tools.yaml
+++ b/roles/kubernetes/tasks/tools.yaml
@@ -4,23 +4,27 @@
   block:
     - name: Download and install Cilium CLI
       ansible.builtin.shell: |
+        set -e
         CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
+        if [ -z "${CILIUM_CLI_VERSION}" ]; then
+          echo "Failed to fetch Cilium CLI version"
+          exit 1
+        fi
         CLI_ARCH=amd64
-        if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
-        curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
-        sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
-        sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
-        rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
+        echo "Installing Cilium CLI version ${CILIUM_CLI_VERSION} for ${CLI_ARCH}"
+        curl -L --fail -o cilium-linux-${CLI_ARCH}.tar.gz https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz
+        sudo tar xzvf cilium-linux-${CLI_ARCH}.tar.gz -C /usr/local/bin
+        rm -f cilium-linux-${CLI_ARCH}.tar.gz
+      become: true
 
     - name: Download and install Hubble
       ansible.builtin.shell: |
         HUBBLE_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/hubble/master/stable.txt)
         HUBBLE_ARCH=amd64
-        if [ "$(uname -m)" = "aarch64" ]; then HUBBLE_ARCH=arm64; fi
-        curl -L --fail --remote-name-all https://github.com/cilium/hubble/releases/download/$HUBBLE_VERSION/hubble-linux-${HUBBLE_ARCH}.tar.gz{,.sha256sum}
-        sha256sum --check hubble-linux-${HUBBLE_ARCH}.tar.gz.sha256sum
-        sudo tar xzvfC hubble-linux-${HUBBLE_ARCH}.tar.gz /usr/local/bin
-        rm hubble-linux-${HUBBLE_ARCH}.tar.gz{,.sha256sum}
+        echo "Installing Hubble version ${HUBBLE_VERSION} for ${HUBBLE_ARCH}"
+        curl -L --fail -o hubble-linux-${HUBBLE_ARCH}.tar.gz https://github.com/cilium/hubble/releases/download/$HUBBLE_VERSION/hubble-linux-${HUBBLE_ARCH}.tar.gz
+        sudo tar xzvf hubble-linux-${HUBBLE_ARCH}.tar.gz -C /usr/local/bin
+        rm -f hubble-linux-${HUBBLE_ARCH}.tar.gz
 
     - name: Add Helm repository key
       ansible.builtin.shell: |
